export const AppStrings = {
  roomRental: 'Room Rental',
  explaination1: `This is Room Rental Application. You can easily book the room forstay. It is special for Tourism people`,
  explaination2: `We would prefer to select the BOOKING button to book the room because ON RENT button for admin to add the room for you`,
  email: 'Email',
  password: 'Password',
  lastName: 'Last Name',
  fistName: 'First Name',
  heyThere: 'Hey there,',
  creatAnAccount: 'Create An Account',
  haveAnAccount: 'Already have an account?',
  login: 'Login',
  welcome: 'Welcome Back',
  doHaveAccount: 'Do you have an account?',
  signIn: 'Sign In',
  roomRental: 'Room Rental',
  email: 'Email',
  close: 'Close',
  help: 'Help',
  contactForHelp: 'Contact us for help',
  admin: 'Welcome Admin',
};
